### PR TITLE
Allow option  to export

### PR DESCRIPTION
**Pull request by EliuX**
# Description

This option allows to specify an expiration date to the command `export`.
With a premium mega account, you can export and generate public folder links by setting the option `expire date`.
```java
    LocalDate expireDate = LocalDate.of(2020, 9, 2);
    final ExportInfo exportInfo = sessionMega.export(exportFolder)
            .setExpireDate(expireDate)
            .call();
```

or you can just specify a duration using `TimeDelay`.

```java  
    final ExportInfo exportInfo = sessionMega.export(exportFolder)
        .setExpirationTimeDelay(TimeDelay.of(
             Period.ofYears(3).plusMonths(11).plusDays(15)
         ))
        .call();
```

As it seems that all the time delays would have the format presented by MegaCmd:

> It indicates the delay in hours(h), days(d),
> minutes(M), seconds(s), months(m) or years(y)
> e.g. "1m12d3h" establish an expiration time 1 month,
> 12 days and 3 hours after the current moment

Instead of using a Representer Pattern, the aforementioned format was returned by the `toString` function of `TimeDelay`. In case that we actually require another representation for a `TimeDelay`, then such part will be refactored and moved to a `Representer` like class.

Further e2e tests will be added by @ccenyo in order to test whether this feature actually works.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 
Please also list any relevant details for your test configuration

- [x] Automated tests 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ccenyo — COMMENTED** [review]
I understand the way you did this, it's actually more readable and cleaner.
i am adding some tests to it.

**Comment by ccenyo** [comment]
I have added some tests and modified ExportInfo to fit the needs. in which branch do you want me to push it?

**Comment by EliuX** [comment]
I pushed the changes you requested. 
Related to
>in which branch do you want me to push it?

Good question! We can do it in 2 ways:
- You give me your approval and I merge these changes into `develop` and in a custom branch of your forked repository you apply your changes (the tests and any other thing you see fit) and create a PR to my `develop` as always.
- You give me your approval and I do not apply any other change to this branch. You pull it and apply your changes into your version of this branch and create a new PR to my `develop`.

I let you choose these or any other alternative you want. 
Thanks for your support!

**Comment by ccenyo** [comment]
Sorry, didn't see your responses, was still waiting for it lol.  Let's do it the second way. i will pull this branch, apply my changes to it and push it to my develop. will make a new PR from there.
Will do it tomorrow. will let you know. thanks

**Comment by EliuX** [comment]
These changes will be applied in #29

**Pull request closed without merging**
